# Generated by Django 5.0.4 on 2024-05-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('Heavily Used', 'HU'), ('Well Used', 'WU'), ('Lightly Used', 'LU'), ('Like New', 'LN'), ('Brand New', 'BN')], max_length=100),
        ),
    ]
