# Generated by Django 5.0.4 on 2024-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('Heavily Used', 'Heavily Used'), ('Well Used', 'Well Used'), ('Lightly Used', 'Lightly Used'), ('Like New', 'Like New'), ('Brand New', 'Brand New')], max_length=100),
        ),
    ]
