# Generated by Django 5.0.4 on 2024-05-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_preference_category_remove_preference_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferredsubcategory',
            options={'verbose_name': 'Preferred Sub-Category', 'verbose_name_plural': 'Preferred Sub-Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('footwear', 'Footwear')], max_length=255, verbose_name='Category Name'),
        ),
    ]
