# Generated by Django 5.0.4 on 2024-05-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('beige', 'Beige'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brownzxc', 'Brown'), ('grey', 'Grey'), ('silver', 'Silver'), ('gold', 'Gold'), ('multi', 'Multi')], max_length=100),
        ),
    ]
