# Generated by Django 5.0.4 on 2024-05-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_preference_category_remove_preference_size_and_more'),
        ('listing', '0005_alter_listing_color'),
    ]

    operations = [
    ]
