# Generated by Django 5.0.4 on 2024-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_merge_20240517_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('beige', 'Beige'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('silver', 'Silver'), ('gold', 'Gold'), ('multi', 'Multi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('HU', 'Heavily Used'), ('WU', 'Well Used'), ('LU', 'Lightly Used'), ('LN', 'Like New'), ('BN', 'Brand New')], max_length=100),
        ),
    ]
