# Generated by Django 5.0.4 on 2024-05-19 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_listing_color_alter_listing_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sub_category', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
