# Generated by Django 5.0.4 on 2024-05-20 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_subcategoryclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryclassification',
            name='listing_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listing.listingimage'),
            preserve_default=False,
        ),
    ]
