# Generated by Django 5.0.4 on 2024-05-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_alter_subcategory_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
