# Generated by Django 5.0.4 on 2024-05-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='category',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='size',
        ),
        migrations.CreateModel(
            name='PreferredSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_sizes', to='listing.preference')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreferredSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_subcategories', to='listing.preference')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
