# Generated by Django 5.0.4 on 2024-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listing_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Beige', 'Beige'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Multi', 'Multi')], max_length=100),
        ),
    ]
