# Generated by Django 5.0.4 on 2024-05-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_category_name'),
        ('listing', '0007_alter_listing_color_alter_listing_condition'),
    ]

    operations = [
    ]
