# Generated by Django 5.0.4 on 2024-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_merge_20240517_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Beige', 'Beige'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Multi', 'Multi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('Heavily Used', 'Heavily Used'), ('Well Used', 'Well Used'), ('Lightly Used', 'Lightly Used'), ('Like New', 'Like New'), ('Brand New', 'Brand New')], max_length=100),
        ),
    ]
