# Generated by Django 5.0.4 on 2024-05-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_subcategoryclassification_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryclassification',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='subcategoryclassification',
            name='listing_image',
        ),
        migrations.AddField(
            model_name='subcategoryclassification',
            name='uploaded_image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
