# Generated by Django 5.0.4 on 2024-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_remove_subcategoryclassification_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women')], default='', max_length=25, null=True),
        ),
    ]
